### ISSUE TITLE
ロードが遅い

### ISSUE THREAD

**Issue by uta8a** [uta8a/web-issue-list#13]
# 現象

- ロードが遅い。repositoryが表示されるまでに数秒かかる

# 理由

- おそらく以下のようにdeveloper tool  > consoleのログが出ているので、409のAPIを叩いている間描画されず遅くなっている

![スクリーンショット 2022-04-30 6 35 46](https://user-images.githubusercontent.com/31395466/166072602-0dc5a2d2-a93f-4572-a84d-e9465e1d1981.png)

# 手順

- commitのないリポジトリに対する処理を行う
- commitがない場合は複数回APIを叩きにいくのをやめるようにする。これはtry catchとかでなんとかなる？
- octokitが複数問い合わせしている気がするので、fetchに置き換えてしまう ref. https://github.com/uta8a/web-issue-list/issues/13#issuecomment-1114226465

**Comment by plageoj** [comment]
この複数回問い合わせをやるのは octkit がやってる気がします。どうせ認証まわりは使っていないのだから、生の`fetch`に書き換えるのが早いかも？

**Comment by uta8a** [comment]
これ確かにと思いました。fetchに置き換える方針でいきます
